### ISSUE TITLE
Cannot access course back-end details

### ISSUE THREAD

**Issue by nataliko** [Andreas-Schoenefeldt/simple-courses#10]
http://lotus-moon.de/Proj/viszerale-therapie.at/backend/web/app_dev.php/Kurs/234
![screen shot 2015-12-15 at 12 55 58](https://cloud.githubusercontent.com/assets/16244792/11811096/3813104e-a32b-11e5-9f27-4b0e9cc95be1.png)

**Comment by Andreas-Schoenefeldt** [comment]
This looks like a timout - unfortunatly this can not realy be fixed... The message states already to please reload the page, so I will close this one.
