### ISSUE TITLE
'Close course' button is not responding 

### ISSUE THREAD

**Issue by nataliko** [Andreas-Schoenefeldt/simple-courses#11]
http://lotus-moon.de/Proj/viszerale-therapie.at/backend/web/app_dev.php/Kurs/224

![screen shot 2015-12-15 at 13 11 47](https://cloud.githubusercontent.com/assets/16244792/11811456/87098cf8-a32d-11e5-9f2f-079f9f79b89c.png)

**Comment by Andreas-Schoenefeldt** [comment]
Seems to work again...
