### ISSUE TITLE
List of teachers is doubled

### ISSUE THREAD

**Issue by nataliko** [Andreas-Schoenefeldt/simple-courses#13]
When creating a new course and choosing the leading teachers, the drop-down menu shows a duplicated list.

![screen shot 2015-12-15 at 17 31 14](https://cloud.githubusercontent.com/assets/16244792/11818347/cf5e3714-a351-11e5-91e8-b5a698058d36.png)

**Comment by Andreas-Schoenefeldt** [comment]
Fixed :)
