### ISSUE TITLE
'Resend registration e-mail' button is not responding

### ISSUE THREAD

**Issue by nataliko** [Andreas-Schoenefeldt/simple-courses#18]
![screen shot 2015-12-15 at 18 24 39](https://cloud.githubusercontent.com/assets/16244792/11819716/43cad11e-a359-11e5-9bd5-391c5f2d0d51.png)

**Comment by Andreas-Schoenefeldt** [comment]
Wohoo, finally fixed!

**Comment by nmxmx** [comment]
Check ob Resend Registration Email funktioniert für einen Teilnehmer:
Wo: 
- Kursübersicht / Registered/ Actions: Pfeiltaste "Resend registration e-mail"
- Extra Fenster öffnet sich- klick auf Button "YES"
- extra Feld rechts oben "error while sending email"

![grafik](https://user-images.githubusercontent.com/44013971/51701770-2ecf8c80-1fe0-11e9-9e70-f4930287fe96.png)
