### ISSUE TITLE
On-line registration allows double booking

### ISSUE THREAD

**Issue by nataliko** [Andreas-Schoenefeldt/simple-courses#9]
I have registered twice for the same course. Is there any chance to block double booking? Like a message saying 'you are already registered for this course'.
http://lotus-moon.de/Proj/viszerale-therapie.at/backend/web/app_dev.php/Kurs/224
![screen shot 2015-12-15 at 12 51 18](https://cloud.githubusercontent.com/assets/16244792/11811018/931a4d0a-a32a-11e5-8147-008304f166cf.png)

**Comment by Andreas-Schoenefeldt** [comment]
I wil not fix this one for now, because it requires quite an efford to register twice and the user gets a confirmation email, which should be enough of a reminder.
